[package]
name = "portal"
version = "0.1.5"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "portal"
path = "src/lib.rs"

[[bin]]
name = "portal"
path = "src/main.rs"

[dependencies]
async-std = "1.12.0"
eframe = { version = "0.20.1", features = ["dark-light", "persistence"] }
egui = { version = "0.20.1" }
futures = "0.3.26"
opener = "0.5.2"
poll-promise = { version = "0.2.0", features = ["async-std"] }
portal-proc-macro = { path = "crates/portal-proc-macro" }
portal-wormhole = { path = "crates/portal-wormhole" }
rfd = "0.11.0"
take_mut = "0.2.2"
tracing-subscriber = "0.3"
ubyte = "0.10.3"

[patch.crates-io]
eframe = { git = "https://github.com/emilk/egui.git" }
egui = { git = "https://github.com/emilk/egui.git" }
poll-promise = { git = "https://github.com/bash/poll-promise", branch = "async-std" }

[workspace]
members = [
    "crates/portal-proc-macro",
    "crates/portal-wormhole",
]

[build-dependencies]
embed-resource = "1.4"
