[package]
name = "portal"
version = "0.1.9"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "portal"
path = "src/lib.rs"

[[bin]]
name = "portal"
path = "src/main.rs"

[dependencies]
async-std = "1.12.0"
color-hex = "0.2.0"
eframe = { version = "0.21.0", default-features = false, features = ["accesskit", "glow", "dark-light", "persistence"] }
egui = { version = "0.21.0", default-features = false, features = ["color-hex"] }
futures = "0.3.26"
opener = { version = "0.5.2", features = ["reveal"] }
poll-promise = { version = "0.2.0", features = ["async-std"] }
portal-proc-macro = { path = "crates/portal-proc-macro" }
portal-wormhole = { path = "crates/portal-wormhole" }
rfd = "0.11.0"
take_mut = "0.2.2"
tracing-subscriber = "0.3"
ubyte = "0.10.3"
winapi = "0.3.9"

[patch.crates-io]
eframe = { git = "https://github.com/bash/egui.git", branch = "theme-changed" }
egui = { git = "https://github.com/bash/egui.git", branch = "theme-changed" }
poll-promise = { git = "https://github.com/EmbarkStudios/poll-promise" }
opener = { git = "https://github.com/bash/opener", branch = "reveal" }

[workspace]
members = [
    "crates/portal-proc-macro",
    "crates/portal-wormhole",
]

[target.'cfg(windows)'.build-dependencies]
ico-builder = { git = "https://github.com/bash/ico-builder.git" }
winresource = "0.1.15"
