[workspace]
members = [
    "crates/portal-proc-macro",
    "crates/portal"
]
resolver = "2"


[patch.crates-io]
eframe = { git = "https://github.com/emilk/egui.git" }
egui = { git = "https://github.com/emilk/egui.git" }
