[package]
name = "portal-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = { version = "2.0.40", features = ["full"] }

[lints]
workspace = true
