name: CI

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}
      - name: Install dependencies
        run: |
          sudo apt-get install librust-atk-dev libgtk-3-dev
        if: runner.os == 'linux'
      - name: Build & run tests
        run: cargo test
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}
      - name: Install dependencies
        run: |
          sudo apt-get install librust-atk-dev libgtk-3-dev
      - name: Run doc tests with all features (this also compiles README examples)
        run: cargo test --doc --all-features
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - name: Install dependencies
        run: |
          sudo apt-get install librust-atk-dev libgtk-3-dev
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings
      - name: Check for typos
        uses: crate-ci/typos@v1.21.0
